[package]
name = "sicl4_interchange"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sicl4_db = { path = "../sicl4_db" }
yosys-netlist-json = { version = "0.1.0", default-features = false }
